version: 2
jobs:
  build:
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
          
      - run:
          name: Build erlang image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            cd erlang
            make release