version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # - setup_remote_docker:
      #     docker_layer_caching: true
      #     version: 18.06.0-ce
          
      - run:
          name: Build erlang image
          command: |
            echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
            cd alpine-erlang
            make release