version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Login to docker
          command: echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
      # - run:
      #     name: Build erlang image
      #     command: |
      #       cd alpine-erlang
      #       make release
      #       cd ..

      - run:
          name: Build elixir image
          command: |
            cd alpine-elixir
            make release